import type { Metadata } from "next";
import "../styles/globals.scss";
import Navigation from "@/components/Navigation";
import Main from "@/components/Main";
import Logo from "@/components/Logo";
import LenisScroll from "@/components/LenisScroll";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <LenisScroll />
                <Navigation Logo={<Logo />} />
                <Main>{children}</Main>
            </body>
        </html>
    );
}
