import type { Metadata } from "next";
import "../styles/globals.scss";
import Navigation from "@/components/Navigation/Navigation";
import Main from "@/components/Main";
import Logo from "@/components/Logo";
import LenisScroll from "@/components/LenisScroll";
import GlobalControls from "@/components/GlobalControls";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <LenisScroll />
                <GlobalControls>
                    <Navigation
                        Logo={<Logo />}
                        routes={[
                            {
                                name: "Strona Główna",
                                link: "/",
                            },
                            {
                                name: "Opinie",
                                link: "/",
                            },
                        ]}
                    />
                    <Main>{children}</Main>
                </GlobalControls>
            </body>
        </html>
    );
}
