import type { Metadata } from "next";
import "../styles/globals.scss";
import Navigation from "@/components/Navigation/Navigation";
import Main from "@/components/Main";
import GlobalControls from "@/components/GlobalControls";
import Footer from "@/components/Footer";
import { NavigationRoutes } from "@/components/Navigation/Navigation.d";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const routes: NavigationRoutes = [
    { name: "Home", link: "/" },
    { name: "O nas", link: "about" },
    { name: "Usługi", link: "/services" },
];

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="">
                <GlobalControls>
                    <Navigation routes={routes} />
                    <Main>{children}</Main>
                    <Footer routes={routes} />
                </GlobalControls>
            </body>
        </html>
    );
}
